kind: pipeline
type: docker
name: deploy_hugo

steps:
- name: build
  image: klakegg/hugo
  environment:
    HUGO_ENVIRONMENT: production
    HUGO_ENV: production

- name: push
  image: appleboy/drone-git-push
  environment:
    PLUGIN_SSH_KEY:
      from_secret: GIT_SSH_PRIVATE
    PLUGIN_REMOTE: ssh://git@hyang.xyz/hyang/hyang.xyz.git
    PLUGIN_PULL: true
    PLUGIN_COMMIT_MESSAGE: [ci] Deploy page
