kind: pipeline
type: docker
name: deploy_hugo

steps:
- name: build
  image: klakegg/hugo
  environment:
    HUGO_ENVIRONMENT: production
    HUGO_ENV: production

- name: push
  image: debian:bookworm-slim
  environment:
    GIT_PUB:
      from_secret: GIT_SSH_PUBLIC
    GIT_SEC:
      from_secret: GIT_SSH_PRIVATE
  commands:
    - apt-get install git -y
    - ls

