kind: pipeline
type: docker
name: deploy_hugo

steps:
- name: build
  image: klakegg/hugo
  environment:
    HUGO_ENVIRONMENT: production
    HUGO_ENV: production

- name: push
  image: appleboy/drone-git-push
  settings:
    pull: true
    remote: ssh://git@hyang.xyz/hyang/hyang.xyz.git
    branch: master
    commit_message: "[ci] Deploy page"
    ssh_key:
      from_secret: GIT_SSH_PRIVATE
