kind: pipeline
type: docker
name: deploy_hugo

steps:
- name: build
  image: klakegg/hugo
  environment:
    HUGO_ENVIRONMENT: production
    HUGO_ENV: production

- name: push
  image: debian:bookworm-slim
  environment:
    GIT_PUB:
      from_secret: GIT_SSH_PUBLIC
    GIT_SEC:
      from_secret: GIT_SSH_PRIVATE
  commands:
    - apt-get update
    - apt-get install git -y
    - mkdir ~/.ssh
    - echo "$GIT_PUB" > ~/.ssh/id_ed25519.pub
    - echo "$GIT_PUB" > ~/.ssh/id_ed25519
    - ls
    - git init
    - git add .
    - git commit -m 'comit'
    - git remote add origin 'git@hyang.xyz:hyang/pages.git'
    - git push -f origin

