kind: pipeline
type: docker
name: deploy_hugo

steps:
- name: submodules
  commands:
    - git submodule update --recursive --remote

- name: build
  image: klakegg/hugo

- name: push
  image: 3gigs/git-push
  environment:
    GIT_SSH_KEY:
      from_secret: GIT_SSH_PRIVATE
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
  commands:
    - mkdir ~/.ssh
    - umask 077
    - echo "$GIT_SSH_KEY" > ~/.ssh/id_ed25519
    - umask 000
    - cd public
    - git config init.defaultBranch master
    - git init
    - git remote add origin git@hyang.xyz:hyang/pages.git
    - git add .
    - git commit -m '[ci] deploy'
    - git push -f -u origin master
 
- name: bing
  image: curlimages/curl
  commands:
    - curl -X PUT https://hyang.xyz
