kind: pipeline
type: docker
name: deploy_hugo

steps:
- name: build
  image: klakegg/hugo
  environment:
    HUGO_ENVIRONMENT: production
    HUGO_ENV: production

- name: push
  image: debian
  environment:
    GIT_SSH_KEY:
      from_secret: GIT_SSH_PRIVATE
  commands:
    - mkdir ~/.ssh
    - echo "$GIT_SSH_KEY" > ~/.ssh/id_ed25519
    - apt-get update && apt-get install git -y
    - cd public
    - git init
    - git remote add origin git@hyang.xyz:hyang/hyang.xyz.git
    - git add .
    - git commit -m '[ci] deploy'
    - git push -f -u origin master
