kind: pipeline
type: docker
name: deploy_hugo

steps:
- name: build
  image: klakegg/hugo
  environment:
    HUGO_ENVIRONMENT: production
    HUGO_ENV: production

- name: push
  image: appleboy/drone-git-push
  settings:
    ssh_key:
      from_secret: GIT_SSH_PRIVATE
    remote: ssh://git@hyang.xyz/hyang/hyang.xyz.git
    commit_message: [ci] Deploy page
