version: '3'
services:
  hugo:
    image: klakegg/hugo
    command: serve --baseURL hyang.xyz
    ports:
      - "1313:1313"
    volumes:
      - ./:/src
    environment:
      - HUGO_ENV=production

