baseURL = 'https://hyang.xyz'
languageCode = 'en-us'
title = "hyang's homepage"
theme = 'papermodx'
paginate = 5

[params]
  description = "Cool blogpostings"
  author = "hyang"
  mainSections = ["post"]
  TocOpen = true
  TocSide = "left"

[params.homeInfoParams]
Title = "👋 Welcome to my homepage"
Content = """
I'm Huaxuan Yang. On *hyang.xyz*, I self-host a bunch of services (including this blog), using the finest grade gaming hardware. Here, I mostly talk about technology stuff, like Linux, programming, etc. Maybe some other content soon...
"""

[languages]
    [languages.en.params.logo]
      logoText = "@hyang.xyz"
      logoHomeLink = "/"
