baseURL = 'https://hyang.xyz'
languageCode = 'en-us'
title = "hyang's homepage"
theme = 'papermodx'
enableRobotsTXT = true
paginate = 5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  description = "Cool blogpostings"
  author = "hyang"
  email = "hyang@hyang.xyz"
  keywords = [ "Blog", "Portfolio" ]
  mainSections = ["posts"]
  TocOpen = true
  TocSide = "left"
  ShowReadingTime = true
  ShowWordCount = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  env = "production"

  [[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1
  [[menu.main]]
  name = "Search"
  url = "/search"
  weight = 2

  [[params.socialIcons]]
  name = "email"
  url = "mailto:hyang@hyang.xyz"
  [[params.socialIcons]]
  name = "github-simple"
  url = "https://github.com/yanghuaxuan"
  [[params.socialIcons]]
  name = "pleroma"
  url = "https://post.hyang.xyz/hyang"
  [[params.socialIcons]]
  name = "linkedin-simple"
  url = "https://www.linkedin.com/in/huaxuan-yang/"


  [params.homeInfoParams]
  Title = "👋 Welcome to my homepage"
  Content = """
  I'm Huaxuan Yang. On *hyang.xyz*, I self-host a bunch of services (including this blog), using the finest grade gaming hardware. Here, I mostly talk about technology stuff, like Linux, programming, etc. Maybe some other content soon...
  """

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]

[languages]
    [languages.en.params.logo]
      logoText = "@hyang.xyz"
      logoHomeLink = "/"
