baseURL = 'https://hyang.xyz'
languageCode = 'en-us'
title = "Huaxuan's Homepage"
theme = 'github-style'

[params]
  author = "hyang"
  description = "@hyang.xyz"
  github = "yanghuaxuan"
  email = "hyang@hyang.xyz"
  url = "https://hyang.xyz"
  keywords = "blog"
  rss = true
  lastmod = true
  userStatusEmoji = "😭"
